apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  POSTGRES_USER: YWxvbw==  
  POSTGRES_PASSWORD: YWxvbw==  
  POSTGRES_DB: bXlkYg== 
  db-url: cG9zdGdyZXNxbDovL2Fsb286YWxvb0Bwb3N0Z3Jlcy1kYi1zZXJ2aWNlOjU0MzIvZGF0YWJhc2U=  
